// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for flow_ffi
class FlowCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlowCoreBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlowCoreBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> flow_get_last_error() {
    return _flow_get_last_error();
  }

  late final _flow_get_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'flow_get_last_error');
  late final _flow_get_last_error =
      _flow_get_last_errorPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  void flow_clear_error() {
    return _flow_clear_error();
  }

  late final _flow_clear_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('flow_clear_error');
  late final _flow_clear_error =
      _flow_clear_errorPtr.asFunction<void Function()>();

  void flow_set_error(
    int code,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _flow_set_error(
      code,
      message,
    );
  }

  late final _flow_set_errorPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Int32, ffi.Pointer<ffi.Char>)>>(
      'flow_set_error');
  late final _flow_set_error = _flow_set_errorPtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Char>)>();

  bool flow_is_valid_handle(
    ffi.Pointer<ffi.Void> handle,
  ) {
    return _flow_is_valid_handle(
      handle,
    );
  }

  late final _flow_is_valid_handlePtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<ffi.Void>)>>(
          'flow_is_valid_handle');
  late final _flow_is_valid_handle = _flow_is_valid_handlePtr
      .asFunction<bool Function(ffi.Pointer<ffi.Void>)>();

  void flow_retain_handle(
    ffi.Pointer<ffi.Void> handle,
  ) {
    return _flow_retain_handle(
      handle,
    );
  }

  late final _flow_retain_handlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'flow_retain_handle');
  late final _flow_retain_handle =
      _flow_retain_handlePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void flow_release_handle(
    ffi.Pointer<ffi.Void> handle,
  ) {
    return _flow_release_handle(
      handle,
    );
  }

  late final _flow_release_handlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'flow_release_handle');
  late final _flow_release_handle = _flow_release_handlePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  int flow_get_ref_count(
    ffi.Pointer<ffi.Void> handle,
  ) {
    return _flow_get_ref_count(
      handle,
    );
  }

  late final _flow_get_ref_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>>(
          'flow_get_ref_count');
  late final _flow_get_ref_count =
      _flow_get_ref_countPtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  FlowEnvHandle flow_env_create(
    int max_threads,
  ) {
    return _flow_env_create(
      max_threads,
    );
  }

  late final _flow_env_createPtr =
      _lookup<ffi.NativeFunction<FlowEnvHandle Function(ffi.Int32)>>(
          'flow_env_create');
  late final _flow_env_create =
      _flow_env_createPtr.asFunction<FlowEnvHandle Function(int)>();

  void flow_env_destroy(
    FlowEnvHandle env,
  ) {
    return _flow_env_destroy(
      env,
    );
  }

  late final _flow_env_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(FlowEnvHandle)>>(
          'flow_env_destroy');
  late final _flow_env_destroy =
      _flow_env_destroyPtr.asFunction<void Function(FlowEnvHandle)>();

  FlowNodeFactoryHandle flow_env_get_factory(
    FlowEnvHandle env,
  ) {
    return _flow_env_get_factory(
      env,
    );
  }

  late final _flow_env_get_factoryPtr = _lookup<
          ffi.NativeFunction<FlowNodeFactoryHandle Function(FlowEnvHandle)>>(
      'flow_env_get_factory');
  late final _flow_env_get_factory = _flow_env_get_factoryPtr
      .asFunction<FlowNodeFactoryHandle Function(FlowEnvHandle)>();

  int flow_env_wait(
    FlowEnvHandle env,
  ) {
    return _flow_env_wait(
      env,
    );
  }

  late final _flow_env_waitPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(FlowEnvHandle)>>(
          'flow_env_wait');
  late final _flow_env_wait =
      _flow_env_waitPtr.asFunction<int Function(FlowEnvHandle)>();

  ffi.Pointer<ffi.Char> flow_env_get_var(
    FlowEnvHandle env,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _flow_env_get_var(
      env,
      name,
    );
  }

  late final _flow_env_get_varPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowEnvHandle, ffi.Pointer<ffi.Char>)>>('flow_env_get_var');
  late final _flow_env_get_var = _flow_env_get_varPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(FlowEnvHandle, ffi.Pointer<ffi.Char>)>();

  FlowGraphHandle flow_graph_create(
    FlowEnvHandle env,
  ) {
    return _flow_graph_create(
      env,
    );
  }

  late final _flow_graph_createPtr =
      _lookup<ffi.NativeFunction<FlowGraphHandle Function(FlowEnvHandle)>>(
          'flow_graph_create');
  late final _flow_graph_create = _flow_graph_createPtr
      .asFunction<FlowGraphHandle Function(FlowEnvHandle)>();

  void flow_graph_destroy(
    FlowGraphHandle graph,
  ) {
    return _flow_graph_destroy(
      graph,
    );
  }

  late final _flow_graph_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(FlowGraphHandle)>>(
          'flow_graph_destroy');
  late final _flow_graph_destroy =
      _flow_graph_destroyPtr.asFunction<void Function(FlowGraphHandle)>();

  FlowNodeHandle flow_graph_add_node(
    FlowGraphHandle graph,
    ffi.Pointer<ffi.Char> class_id,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _flow_graph_add_node(
      graph,
      class_id,
      name,
    );
  }

  late final _flow_graph_add_nodePtr = _lookup<
      ffi.NativeFunction<
          FlowNodeHandle Function(FlowGraphHandle, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('flow_graph_add_node');
  late final _flow_graph_add_node = _flow_graph_add_nodePtr.asFunction<
      FlowNodeHandle Function(
          FlowGraphHandle, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  int flow_graph_remove_node(
    FlowGraphHandle graph,
    ffi.Pointer<ffi.Char> node_id,
  ) {
    return _flow_graph_remove_node(
      graph,
      node_id,
    );
  }

  late final _flow_graph_remove_nodePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowGraphHandle,
              ffi.Pointer<ffi.Char>)>>('flow_graph_remove_node');
  late final _flow_graph_remove_node = _flow_graph_remove_nodePtr
      .asFunction<int Function(FlowGraphHandle, ffi.Pointer<ffi.Char>)>();

  FlowNodeHandle flow_graph_get_node(
    FlowGraphHandle graph,
    ffi.Pointer<ffi.Char> node_id,
  ) {
    return _flow_graph_get_node(
      graph,
      node_id,
    );
  }

  late final _flow_graph_get_nodePtr = _lookup<
      ffi.NativeFunction<
          FlowNodeHandle Function(
              FlowGraphHandle, ffi.Pointer<ffi.Char>)>>('flow_graph_get_node');
  late final _flow_graph_get_node = _flow_graph_get_nodePtr.asFunction<
      FlowNodeHandle Function(FlowGraphHandle, ffi.Pointer<ffi.Char>)>();

  int flow_graph_get_nodes(
    FlowGraphHandle graph,
    ffi.Pointer<ffi.Pointer<FlowNodeHandle>> nodes,
    ffi.Pointer<ffi.Size> count,
  ) {
    return _flow_graph_get_nodes(
      graph,
      nodes,
      count,
    );
  }

  late final _flow_graph_get_nodesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              FlowGraphHandle,
              ffi.Pointer<ffi.Pointer<FlowNodeHandle>>,
              ffi.Pointer<ffi.Size>)>>('flow_graph_get_nodes');
  late final _flow_graph_get_nodes = _flow_graph_get_nodesPtr.asFunction<
      int Function(FlowGraphHandle, ffi.Pointer<ffi.Pointer<FlowNodeHandle>>,
          ffi.Pointer<ffi.Size>)>();

  FlowConnectionHandle flow_graph_connect_nodes(
    FlowGraphHandle graph,
    ffi.Pointer<ffi.Char> source_id,
    ffi.Pointer<ffi.Char> source_port,
    ffi.Pointer<ffi.Char> target_id,
    ffi.Pointer<ffi.Char> target_port,
  ) {
    return _flow_graph_connect_nodes(
      graph,
      source_id,
      source_port,
      target_id,
      target_port,
    );
  }

  late final _flow_graph_connect_nodesPtr = _lookup<
      ffi.NativeFunction<
          FlowConnectionHandle Function(
              FlowGraphHandle,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('flow_graph_connect_nodes');
  late final _flow_graph_connect_nodes =
      _flow_graph_connect_nodesPtr.asFunction<
          FlowConnectionHandle Function(
              FlowGraphHandle,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>();

  int flow_graph_disconnect_nodes(
    FlowGraphHandle graph,
    ffi.Pointer<ffi.Char> connection_id,
  ) {
    return _flow_graph_disconnect_nodes(
      graph,
      connection_id,
    );
  }

  late final _flow_graph_disconnect_nodesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowGraphHandle,
              ffi.Pointer<ffi.Char>)>>('flow_graph_disconnect_nodes');
  late final _flow_graph_disconnect_nodes = _flow_graph_disconnect_nodesPtr
      .asFunction<int Function(FlowGraphHandle, ffi.Pointer<ffi.Char>)>();

  int flow_graph_get_connections(
    FlowGraphHandle graph,
    ffi.Pointer<ffi.Pointer<FlowConnectionInfo>> connections,
    ffi.Pointer<ffi.Size> count,
  ) {
    return _flow_graph_get_connections(
      graph,
      connections,
      count,
    );
  }

  late final _flow_graph_get_connectionsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              FlowGraphHandle,
              ffi.Pointer<ffi.Pointer<FlowConnectionInfo>>,
              ffi.Pointer<ffi.Size>)>>('flow_graph_get_connections');
  late final _flow_graph_get_connections =
      _flow_graph_get_connectionsPtr.asFunction<
          int Function(
              FlowGraphHandle,
              ffi.Pointer<ffi.Pointer<FlowConnectionInfo>>,
              ffi.Pointer<ffi.Size>)>();

  bool flow_graph_can_connect(
    FlowGraphHandle graph,
    ffi.Pointer<ffi.Char> source_id,
    ffi.Pointer<ffi.Char> source_port,
    ffi.Pointer<ffi.Char> target_id,
    ffi.Pointer<ffi.Char> target_port,
  ) {
    return _flow_graph_can_connect(
      graph,
      source_id,
      source_port,
      target_id,
      target_port,
    );
  }

  late final _flow_graph_can_connectPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(
              FlowGraphHandle,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('flow_graph_can_connect');
  late final _flow_graph_can_connect = _flow_graph_can_connectPtr.asFunction<
      bool Function(
          FlowGraphHandle,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  int flow_graph_run(
    FlowGraphHandle graph,
  ) {
    return _flow_graph_run(
      graph,
    );
  }

  late final _flow_graph_runPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(FlowGraphHandle)>>(
          'flow_graph_run');
  late final _flow_graph_run =
      _flow_graph_runPtr.asFunction<int Function(FlowGraphHandle)>();

  int flow_graph_clear(
    FlowGraphHandle graph,
  ) {
    return _flow_graph_clear(
      graph,
    );
  }

  late final _flow_graph_clearPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(FlowGraphHandle)>>(
          'flow_graph_clear');
  late final _flow_graph_clear =
      _flow_graph_clearPtr.asFunction<int Function(FlowGraphHandle)>();

  ffi.Pointer<ffi.Char> flow_graph_save_to_json(
    FlowGraphHandle graph,
  ) {
    return _flow_graph_save_to_json(
      graph,
    );
  }

  late final _flow_graph_save_to_jsonPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(FlowGraphHandle)>>(
      'flow_graph_save_to_json');
  late final _flow_graph_save_to_json = _flow_graph_save_to_jsonPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowGraphHandle)>();

  int flow_graph_load_from_json(
    FlowGraphHandle graph,
    ffi.Pointer<ffi.Char> json,
  ) {
    return _flow_graph_load_from_json(
      graph,
      json,
    );
  }

  late final _flow_graph_load_from_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowGraphHandle,
              ffi.Pointer<ffi.Char>)>>('flow_graph_load_from_json');
  late final _flow_graph_load_from_json = _flow_graph_load_from_jsonPtr
      .asFunction<int Function(FlowGraphHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> flow_node_save_to_json(
    FlowNodeHandle node,
  ) {
    return _flow_node_save_to_json(
      node,
    );
  }

  late final _flow_node_save_to_jsonPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(FlowNodeHandle)>>(
      'flow_node_save_to_json');
  late final _flow_node_save_to_json = _flow_node_save_to_jsonPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowNodeHandle)>();

  int flow_node_load_from_json(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> json_str,
  ) {
    return _flow_node_load_from_json(
      node,
      json_str,
    );
  }

  late final _flow_node_load_from_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowNodeHandle,
              ffi.Pointer<ffi.Char>)>>('flow_node_load_from_json');
  late final _flow_node_load_from_json = _flow_node_load_from_jsonPtr
      .asFunction<int Function(FlowNodeHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> flow_node_get_id(
    FlowNodeHandle node,
  ) {
    return _flow_node_get_id(
      node,
    );
  }

  late final _flow_node_get_idPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(FlowNodeHandle)>>(
      'flow_node_get_id');
  late final _flow_node_get_id = _flow_node_get_idPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowNodeHandle)>();

  ffi.Pointer<ffi.Char> flow_node_get_name(
    FlowNodeHandle node,
  ) {
    return _flow_node_get_name(
      node,
    );
  }

  late final _flow_node_get_namePtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(FlowNodeHandle)>>(
      'flow_node_get_name');
  late final _flow_node_get_name = _flow_node_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowNodeHandle)>();

  ffi.Pointer<ffi.Char> flow_node_get_class(
    FlowNodeHandle node,
  ) {
    return _flow_node_get_class(
      node,
    );
  }

  late final _flow_node_get_classPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(FlowNodeHandle)>>(
      'flow_node_get_class');
  late final _flow_node_get_class = _flow_node_get_classPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowNodeHandle)>();

  int flow_node_set_name(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> name,
  ) {
    return _flow_node_set_name(
      node,
      name,
    );
  }

  late final _flow_node_set_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              FlowNodeHandle, ffi.Pointer<ffi.Char>)>>('flow_node_set_name');
  late final _flow_node_set_name = _flow_node_set_namePtr
      .asFunction<int Function(FlowNodeHandle, ffi.Pointer<ffi.Char>)>();

  int flow_node_set_input_data(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
    FlowNodeDataHandle data,
  ) {
    return _flow_node_set_input_data(
      node,
      port_key,
      data,
    );
  }

  late final _flow_node_set_input_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowNodeHandle, ffi.Pointer<ffi.Char>,
              FlowNodeDataHandle)>>('flow_node_set_input_data');
  late final _flow_node_set_input_data =
      _flow_node_set_input_dataPtr.asFunction<
          int Function(
              FlowNodeHandle, ffi.Pointer<ffi.Char>, FlowNodeDataHandle)>();

  FlowNodeDataHandle flow_node_get_input_data(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
  ) {
    return _flow_node_get_input_data(
      node,
      port_key,
    );
  }

  late final _flow_node_get_input_dataPtr = _lookup<
      ffi.NativeFunction<
          FlowNodeDataHandle Function(FlowNodeHandle,
              ffi.Pointer<ffi.Char>)>>('flow_node_get_input_data');
  late final _flow_node_get_input_data =
      _flow_node_get_input_dataPtr.asFunction<
          FlowNodeDataHandle Function(FlowNodeHandle, ffi.Pointer<ffi.Char>)>();

  FlowNodeDataHandle flow_node_get_output_data(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
  ) {
    return _flow_node_get_output_data(
      node,
      port_key,
    );
  }

  late final _flow_node_get_output_dataPtr = _lookup<
      ffi.NativeFunction<
          FlowNodeDataHandle Function(FlowNodeHandle,
              ffi.Pointer<ffi.Char>)>>('flow_node_get_output_data');
  late final _flow_node_get_output_data =
      _flow_node_get_output_dataPtr.asFunction<
          FlowNodeDataHandle Function(FlowNodeHandle, ffi.Pointer<ffi.Char>)>();

  int flow_node_clear_input_data(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
  ) {
    return _flow_node_clear_input_data(
      node,
      port_key,
    );
  }

  late final _flow_node_clear_input_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowNodeHandle,
              ffi.Pointer<ffi.Char>)>>('flow_node_clear_input_data');
  late final _flow_node_clear_input_data = _flow_node_clear_input_dataPtr
      .asFunction<int Function(FlowNodeHandle, ffi.Pointer<ffi.Char>)>();

  int flow_node_clear_output_data(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
  ) {
    return _flow_node_clear_output_data(
      node,
      port_key,
    );
  }

  late final _flow_node_clear_output_dataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowNodeHandle,
              ffi.Pointer<ffi.Char>)>>('flow_node_clear_output_data');
  late final _flow_node_clear_output_data = _flow_node_clear_output_dataPtr
      .asFunction<int Function(FlowNodeHandle, ffi.Pointer<ffi.Char>)>();

  int flow_node_invoke_compute(
    FlowNodeHandle node,
  ) {
    return _flow_node_invoke_compute(
      node,
    );
  }

  late final _flow_node_invoke_computePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(FlowNodeHandle)>>(
          'flow_node_invoke_compute');
  late final _flow_node_invoke_compute =
      _flow_node_invoke_computePtr.asFunction<int Function(FlowNodeHandle)>();

  bool flow_node_validate_required_inputs(
    FlowNodeHandle node,
  ) {
    return _flow_node_validate_required_inputs(
      node,
    );
  }

  late final _flow_node_validate_required_inputsPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(FlowNodeHandle)>>(
          'flow_node_validate_required_inputs');
  late final _flow_node_validate_required_inputs =
      _flow_node_validate_required_inputsPtr
          .asFunction<bool Function(FlowNodeHandle)>();

  bool flow_node_has_connected_inputs(
    FlowNodeHandle node,
  ) {
    return _flow_node_has_connected_inputs(
      node,
    );
  }

  late final _flow_node_has_connected_inputsPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(FlowNodeHandle)>>(
          'flow_node_has_connected_inputs');
  late final _flow_node_has_connected_inputs =
      _flow_node_has_connected_inputsPtr
          .asFunction<bool Function(FlowNodeHandle)>();

  bool flow_node_has_connected_outputs(
    FlowNodeHandle node,
  ) {
    return _flow_node_has_connected_outputs(
      node,
    );
  }

  late final _flow_node_has_connected_outputsPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(FlowNodeHandle)>>(
          'flow_node_has_connected_outputs');
  late final _flow_node_has_connected_outputs =
      _flow_node_has_connected_outputsPtr
          .asFunction<bool Function(FlowNodeHandle)>();

  int flow_node_get_input_port_keys(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> port_keys,
    ffi.Pointer<ffi.Size> count,
  ) {
    return _flow_node_get_input_port_keys(
      node,
      port_keys,
      count,
    );
  }

  late final _flow_node_get_input_port_keysPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              FlowNodeHandle,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>>('flow_node_get_input_port_keys');
  late final _flow_node_get_input_port_keys =
      _flow_node_get_input_port_keysPtr.asFunction<
          int Function(
              FlowNodeHandle,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>();

  int flow_node_get_output_port_keys(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> port_keys,
    ffi.Pointer<ffi.Size> count,
  ) {
    return _flow_node_get_output_port_keys(
      node,
      port_keys,
      count,
    );
  }

  late final _flow_node_get_output_port_keysPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              FlowNodeHandle,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>>('flow_node_get_output_port_keys');
  late final _flow_node_get_output_port_keys =
      _flow_node_get_output_port_keysPtr.asFunction<
          int Function(
              FlowNodeHandle,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>();

  ffi.Pointer<ffi.Char> flow_node_get_input_port_type(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
  ) {
    return _flow_node_get_input_port_type(
      node,
      port_key,
    );
  }

  late final _flow_node_get_input_port_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(FlowNodeHandle,
              ffi.Pointer<ffi.Char>)>>('flow_node_get_input_port_type');
  late final _flow_node_get_input_port_type =
      _flow_node_get_input_port_typePtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowNodeHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> flow_node_get_output_port_type(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
  ) {
    return _flow_node_get_output_port_type(
      node,
      port_key,
    );
  }

  late final _flow_node_get_output_port_typePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(FlowNodeHandle,
              ffi.Pointer<ffi.Char>)>>('flow_node_get_output_port_type');
  late final _flow_node_get_output_port_type =
      _flow_node_get_output_port_typePtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowNodeHandle, ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> flow_node_get_port_description(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
    bool is_input_port,
  ) {
    return _flow_node_get_port_description(
      node,
      port_key,
      is_input_port,
    );
  }

  late final _flow_node_get_port_descriptionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(FlowNodeHandle, ffi.Pointer<ffi.Char>,
              ffi.Bool)>>('flow_node_get_port_description');
  late final _flow_node_get_port_description =
      _flow_node_get_port_descriptionPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowNodeHandle, ffi.Pointer<ffi.Char>, bool)>();

  int flow_node_get_port_metadata(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
    ffi.Pointer<FlowPortMetadata> metadata,
  ) {
    return _flow_node_get_port_metadata(
      node,
      port_key,
      metadata,
    );
  }

  late final _flow_node_get_port_metadataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowNodeHandle, ffi.Pointer<ffi.Char>,
              ffi.Pointer<FlowPortMetadata>)>>('flow_node_get_port_metadata');
  late final _flow_node_get_port_metadata =
      _flow_node_get_port_metadataPtr.asFunction<
          int Function(FlowNodeHandle, ffi.Pointer<ffi.Char>,
              ffi.Pointer<FlowPortMetadata>)>();

  int flow_node_get_input_ports_metadata(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Pointer<FlowPortMetadata>> metadata_array,
    ffi.Pointer<ffi.Size> count,
  ) {
    return _flow_node_get_input_ports_metadata(
      node,
      metadata_array,
      count,
    );
  }

  late final _flow_node_get_input_ports_metadataPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              FlowNodeHandle,
              ffi.Pointer<ffi.Pointer<FlowPortMetadata>>,
              ffi.Pointer<ffi.Size>)>>('flow_node_get_input_ports_metadata');
  late final _flow_node_get_input_ports_metadata =
      _flow_node_get_input_ports_metadataPtr.asFunction<
          int Function(
              FlowNodeHandle,
              ffi.Pointer<ffi.Pointer<FlowPortMetadata>>,
              ffi.Pointer<ffi.Size>)>();

  void flow_free_port_metadata_array(
    ffi.Pointer<FlowPortMetadata> metadata_array,
    int count,
  ) {
    return _flow_free_port_metadata_array(
      metadata_array,
      count,
    );
  }

  late final _flow_free_port_metadata_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FlowPortMetadata>,
              ffi.Size)>>('flow_free_port_metadata_array');
  late final _flow_free_port_metadata_array = _flow_free_port_metadata_arrayPtr
      .asFunction<void Function(ffi.Pointer<FlowPortMetadata>, int)>();

  void flow_free_port_metadata(
    ffi.Pointer<FlowPortMetadata> metadata,
  ) {
    return _flow_free_port_metadata(
      metadata,
    );
  }

  late final _flow_free_port_metadataPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<FlowPortMetadata>)>>(
      'flow_free_port_metadata');
  late final _flow_free_port_metadata = _flow_free_port_metadataPtr
      .asFunction<void Function(ffi.Pointer<FlowPortMetadata>)>();

  ffi.Pointer<ffi.Char> flow_connection_get_id(
    FlowConnectionHandle conn,
  ) {
    return _flow_connection_get_id(
      conn,
    );
  }

  late final _flow_connection_get_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowConnectionHandle)>>('flow_connection_get_id');
  late final _flow_connection_get_id = _flow_connection_get_idPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowConnectionHandle)>();

  ffi.Pointer<ffi.Char> flow_connection_get_start_node_id(
    FlowConnectionHandle conn,
  ) {
    return _flow_connection_get_start_node_id(
      conn,
    );
  }

  late final _flow_connection_get_start_node_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowConnectionHandle)>>('flow_connection_get_start_node_id');
  late final _flow_connection_get_start_node_id =
      _flow_connection_get_start_node_idPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(FlowConnectionHandle)>();

  ffi.Pointer<ffi.Char> flow_connection_get_start_port(
    FlowConnectionHandle conn,
  ) {
    return _flow_connection_get_start_port(
      conn,
    );
  }

  late final _flow_connection_get_start_portPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowConnectionHandle)>>('flow_connection_get_start_port');
  late final _flow_connection_get_start_port =
      _flow_connection_get_start_portPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(FlowConnectionHandle)>();

  ffi.Pointer<ffi.Char> flow_connection_get_end_node_id(
    FlowConnectionHandle conn,
  ) {
    return _flow_connection_get_end_node_id(
      conn,
    );
  }

  late final _flow_connection_get_end_node_idPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowConnectionHandle)>>('flow_connection_get_end_node_id');
  late final _flow_connection_get_end_node_id =
      _flow_connection_get_end_node_idPtr
          .asFunction<ffi.Pointer<ffi.Char> Function(FlowConnectionHandle)>();

  ffi.Pointer<ffi.Char> flow_connection_get_end_port(
    FlowConnectionHandle conn,
  ) {
    return _flow_connection_get_end_port(
      conn,
    );
  }

  late final _flow_connection_get_end_portPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowConnectionHandle)>>('flow_connection_get_end_port');
  late final _flow_connection_get_end_port = _flow_connection_get_end_portPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowConnectionHandle)>();

  FlowNodeHandle flow_factory_create_node(
    FlowNodeFactoryHandle factory1,
    ffi.Pointer<ffi.Char> class_name,
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> name,
    FlowEnvHandle env,
  ) {
    return _flow_factory_create_node(
      factory1,
      class_name,
      uuid,
      name,
      env,
    );
  }

  late final _flow_factory_create_nodePtr = _lookup<
      ffi.NativeFunction<
          FlowNodeHandle Function(
              FlowNodeFactoryHandle,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              FlowEnvHandle)>>('flow_factory_create_node');
  late final _flow_factory_create_node =
      _flow_factory_create_nodePtr.asFunction<
          FlowNodeHandle Function(FlowNodeFactoryHandle, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, FlowEnvHandle)>();

  int flow_factory_get_categories(
    FlowNodeFactoryHandle factory1,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> categories,
    ffi.Pointer<ffi.Size> count,
  ) {
    return _flow_factory_get_categories(
      factory1,
      categories,
      count,
    );
  }

  late final _flow_factory_get_categoriesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              FlowNodeFactoryHandle,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>>('flow_factory_get_categories');
  late final _flow_factory_get_categories =
      _flow_factory_get_categoriesPtr.asFunction<
          int Function(
              FlowNodeFactoryHandle,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>();

  int flow_factory_get_node_classes(
    FlowNodeFactoryHandle factory1,
    ffi.Pointer<ffi.Char> category,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>> classes,
    ffi.Pointer<ffi.Size> count,
  ) {
    return _flow_factory_get_node_classes(
      factory1,
      category,
      classes,
      count,
    );
  }

  late final _flow_factory_get_node_classesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              FlowNodeFactoryHandle,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>>('flow_factory_get_node_classes');
  late final _flow_factory_get_node_classes =
      _flow_factory_get_node_classesPtr.asFunction<
          int Function(
              FlowNodeFactoryHandle,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Pointer<ffi.Char>>>,
              ffi.Pointer<ffi.Size>)>();

  ffi.Pointer<ffi.Char> flow_factory_get_friendly_name(
    FlowNodeFactoryHandle factory1,
    ffi.Pointer<ffi.Char> class_name,
  ) {
    return _flow_factory_get_friendly_name(
      factory1,
      class_name,
    );
  }

  late final _flow_factory_get_friendly_namePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(FlowNodeFactoryHandle,
              ffi.Pointer<ffi.Char>)>>('flow_factory_get_friendly_name');
  late final _flow_factory_get_friendly_name =
      _flow_factory_get_friendly_namePtr.asFunction<
          ffi.Pointer<ffi.Char> Function(
              FlowNodeFactoryHandle, ffi.Pointer<ffi.Char>)>();

  bool flow_factory_is_convertible(
    FlowNodeFactoryHandle factory1,
    ffi.Pointer<ffi.Char> from_type,
    ffi.Pointer<ffi.Char> to_type,
  ) {
    return _flow_factory_is_convertible(
      factory1,
      from_type,
      to_type,
    );
  }

  late final _flow_factory_is_convertiblePtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(FlowNodeFactoryHandle, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('flow_factory_is_convertible');
  late final _flow_factory_is_convertible =
      _flow_factory_is_convertiblePtr.asFunction<
          bool Function(FlowNodeFactoryHandle, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>();

  FlowModuleHandle flow_module_create(
    FlowNodeFactoryHandle factory1,
  ) {
    return _flow_module_create(
      factory1,
    );
  }

  late final _flow_module_createPtr = _lookup<
          ffi.NativeFunction<FlowModuleHandle Function(FlowNodeFactoryHandle)>>(
      'flow_module_create');
  late final _flow_module_create = _flow_module_createPtr
      .asFunction<FlowModuleHandle Function(FlowNodeFactoryHandle)>();

  void flow_module_destroy(
    FlowModuleHandle module,
  ) {
    return _flow_module_destroy(
      module,
    );
  }

  late final _flow_module_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(FlowModuleHandle)>>(
          'flow_module_destroy');
  late final _flow_module_destroy =
      _flow_module_destroyPtr.asFunction<void Function(FlowModuleHandle)>();

  int flow_module_load(
    FlowModuleHandle module,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _flow_module_load(
      module,
      path,
    );
  }

  late final _flow_module_loadPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              FlowModuleHandle, ffi.Pointer<ffi.Char>)>>('flow_module_load');
  late final _flow_module_load = _flow_module_loadPtr
      .asFunction<int Function(FlowModuleHandle, ffi.Pointer<ffi.Char>)>();

  int flow_module_unload(
    FlowModuleHandle module,
  ) {
    return _flow_module_unload(
      module,
    );
  }

  late final _flow_module_unloadPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(FlowModuleHandle)>>(
          'flow_module_unload');
  late final _flow_module_unload =
      _flow_module_unloadPtr.asFunction<int Function(FlowModuleHandle)>();

  int flow_module_register_nodes(
    FlowModuleHandle module,
  ) {
    return _flow_module_register_nodes(
      module,
    );
  }

  late final _flow_module_register_nodesPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(FlowModuleHandle)>>(
          'flow_module_register_nodes');
  late final _flow_module_register_nodes = _flow_module_register_nodesPtr
      .asFunction<int Function(FlowModuleHandle)>();

  int flow_module_unregister_nodes(
    FlowModuleHandle module,
  ) {
    return _flow_module_unregister_nodes(
      module,
    );
  }

  late final _flow_module_unregister_nodesPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(FlowModuleHandle)>>(
          'flow_module_unregister_nodes');
  late final _flow_module_unregister_nodes = _flow_module_unregister_nodesPtr
      .asFunction<int Function(FlowModuleHandle)>();

  bool flow_module_is_loaded(
    FlowModuleHandle module,
  ) {
    return _flow_module_is_loaded(
      module,
    );
  }

  late final _flow_module_is_loadedPtr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(FlowModuleHandle)>>(
          'flow_module_is_loaded');
  late final _flow_module_is_loaded =
      _flow_module_is_loadedPtr.asFunction<bool Function(FlowModuleHandle)>();

  ffi.Pointer<ffi.Char> flow_module_get_name(
    FlowModuleHandle module,
  ) {
    return _flow_module_get_name(
      module,
    );
  }

  late final _flow_module_get_namePtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(FlowModuleHandle)>>(
      'flow_module_get_name');
  late final _flow_module_get_name = _flow_module_get_namePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowModuleHandle)>();

  ffi.Pointer<ffi.Char> flow_module_get_version(
    FlowModuleHandle module,
  ) {
    return _flow_module_get_version(
      module,
    );
  }

  late final _flow_module_get_versionPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(FlowModuleHandle)>>(
      'flow_module_get_version');
  late final _flow_module_get_version = _flow_module_get_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowModuleHandle)>();

  ffi.Pointer<ffi.Char> flow_module_get_author(
    FlowModuleHandle module,
  ) {
    return _flow_module_get_author(
      module,
    );
  }

  late final _flow_module_get_authorPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(FlowModuleHandle)>>(
      'flow_module_get_author');
  late final _flow_module_get_author = _flow_module_get_authorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowModuleHandle)>();

  ffi.Pointer<ffi.Char> flow_module_get_description(
    FlowModuleHandle module,
  ) {
    return _flow_module_get_description(
      module,
    );
  }

  late final _flow_module_get_descriptionPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(FlowModuleHandle)>>(
      'flow_module_get_description');
  late final _flow_module_get_description = _flow_module_get_descriptionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowModuleHandle)>();

  FlowNodeDataHandle flow_data_create_int(
    int value,
  ) {
    return _flow_data_create_int(
      value,
    );
  }

  late final _flow_data_create_intPtr =
      _lookup<ffi.NativeFunction<FlowNodeDataHandle Function(ffi.Int32)>>(
          'flow_data_create_int');
  late final _flow_data_create_int =
      _flow_data_create_intPtr.asFunction<FlowNodeDataHandle Function(int)>();

  FlowNodeDataHandle flow_data_create_double(
    double value,
  ) {
    return _flow_data_create_double(
      value,
    );
  }

  late final _flow_data_create_doublePtr =
      _lookup<ffi.NativeFunction<FlowNodeDataHandle Function(ffi.Double)>>(
          'flow_data_create_double');
  late final _flow_data_create_double = _flow_data_create_doublePtr
      .asFunction<FlowNodeDataHandle Function(double)>();

  FlowNodeDataHandle flow_data_create_bool(
    bool value,
  ) {
    return _flow_data_create_bool(
      value,
    );
  }

  late final _flow_data_create_boolPtr =
      _lookup<ffi.NativeFunction<FlowNodeDataHandle Function(ffi.Bool)>>(
          'flow_data_create_bool');
  late final _flow_data_create_bool =
      _flow_data_create_boolPtr.asFunction<FlowNodeDataHandle Function(bool)>();

  FlowNodeDataHandle flow_data_create_string(
    ffi.Pointer<ffi.Char> value,
  ) {
    return _flow_data_create_string(
      value,
    );
  }

  late final _flow_data_create_stringPtr = _lookup<
          ffi
          .NativeFunction<FlowNodeDataHandle Function(ffi.Pointer<ffi.Char>)>>(
      'flow_data_create_string');
  late final _flow_data_create_string = _flow_data_create_stringPtr
      .asFunction<FlowNodeDataHandle Function(ffi.Pointer<ffi.Char>)>();

  int flow_data_get_int(
    FlowNodeDataHandle data,
    ffi.Pointer<ffi.Int32> value,
  ) {
    return _flow_data_get_int(
      data,
      value,
    );
  }

  late final _flow_data_get_intPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowNodeDataHandle,
              ffi.Pointer<ffi.Int32>)>>('flow_data_get_int');
  late final _flow_data_get_int = _flow_data_get_intPtr
      .asFunction<int Function(FlowNodeDataHandle, ffi.Pointer<ffi.Int32>)>();

  int flow_data_get_double(
    FlowNodeDataHandle data,
    ffi.Pointer<ffi.Double> value,
  ) {
    return _flow_data_get_double(
      data,
      value,
    );
  }

  late final _flow_data_get_doublePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowNodeDataHandle,
              ffi.Pointer<ffi.Double>)>>('flow_data_get_double');
  late final _flow_data_get_double = _flow_data_get_doublePtr
      .asFunction<int Function(FlowNodeDataHandle, ffi.Pointer<ffi.Double>)>();

  int flow_data_get_bool(
    FlowNodeDataHandle data,
    ffi.Pointer<ffi.Bool> value,
  ) {
    return _flow_data_get_bool(
      data,
      value,
    );
  }

  late final _flow_data_get_boolPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowNodeDataHandle,
              ffi.Pointer<ffi.Bool>)>>('flow_data_get_bool');
  late final _flow_data_get_bool = _flow_data_get_boolPtr
      .asFunction<int Function(FlowNodeDataHandle, ffi.Pointer<ffi.Bool>)>();

  int flow_data_get_string(
    FlowNodeDataHandle data,
    ffi.Pointer<ffi.Pointer<ffi.Char>> value,
  ) {
    return _flow_data_get_string(
      data,
      value,
    );
  }

  late final _flow_data_get_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(FlowNodeDataHandle,
              ffi.Pointer<ffi.Pointer<ffi.Char>>)>>('flow_data_get_string');
  late final _flow_data_get_string = _flow_data_get_stringPtr.asFunction<
      int Function(FlowNodeDataHandle, ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  ffi.Pointer<ffi.Char> flow_data_get_type(
    FlowNodeDataHandle data,
  ) {
    return _flow_data_get_type(
      data,
    );
  }

  late final _flow_data_get_typePtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<ffi.Char> Function(FlowNodeDataHandle)>>(
      'flow_data_get_type');
  late final _flow_data_get_type = _flow_data_get_typePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowNodeDataHandle)>();

  void flow_data_destroy(
    FlowNodeDataHandle data,
  ) {
    return _flow_data_destroy(
      data,
    );
  }

  late final _flow_data_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(FlowNodeDataHandle)>>(
          'flow_data_destroy');
  late final _flow_data_destroy =
      _flow_data_destroyPtr.asFunction<void Function(FlowNodeDataHandle)>();

  ffi.Pointer<ffi.Char> flow_data_to_string(
    FlowNodeDataHandle data,
  ) {
    return _flow_data_to_string(
      data,
    );
  }

  late final _flow_data_to_stringPtr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<ffi.Char> Function(FlowNodeDataHandle)>>(
      'flow_data_to_string');
  late final _flow_data_to_string = _flow_data_to_stringPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(FlowNodeDataHandle)>();

  void flow_free_string(
    ffi.Pointer<ffi.Char> str,
  ) {
    return _flow_free_string(
      str,
    );
  }

  late final _flow_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'flow_free_string');
  late final _flow_free_string =
      _flow_free_stringPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void flow_free_string_array(
    ffi.Pointer<ffi.Pointer<ffi.Char>> array,
    int count,
  ) {
    return _flow_free_string_array(
      array,
      count,
    );
  }

  late final _flow_free_string_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Size)>>('flow_free_string_array');
  late final _flow_free_string_array = _flow_free_string_arrayPtr
      .asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, int)>();

  void flow_free_handle_array(
    ffi.Pointer<ffi.Pointer<ffi.Void>> array,
  ) {
    return _flow_free_handle_array(
      array,
    );
  }

  late final _flow_free_handle_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Pointer<ffi.Void>>)>>('flow_free_handle_array');
  late final _flow_free_handle_array = _flow_free_handle_arrayPtr
      .asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Void>>)>();

  void flow_free_connection_array(
    ffi.Pointer<FlowConnectionInfo> connections,
    int count,
  ) {
    return _flow_free_connection_array(
      connections,
      count,
    );
  }

  late final _flow_free_connection_arrayPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<FlowConnectionInfo>,
              ffi.Size)>>('flow_free_connection_array');
  late final _flow_free_connection_array = _flow_free_connection_arrayPtr
      .asFunction<void Function(ffi.Pointer<FlowConnectionInfo>, int)>();

  FlowEventRegistrationHandle flow_graph_on_node_added(
    FlowGraphHandle graph,
    FlowNodeEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _flow_graph_on_node_added(
      graph,
      callback,
      user_data,
    );
  }

  late final _flow_graph_on_node_addedPtr = _lookup<
      ffi.NativeFunction<
          FlowEventRegistrationHandle Function(
              FlowGraphHandle,
              FlowNodeEventCallback,
              ffi.Pointer<ffi.Void>)>>('flow_graph_on_node_added');
  late final _flow_graph_on_node_added =
      _flow_graph_on_node_addedPtr.asFunction<
          FlowEventRegistrationHandle Function(
              FlowGraphHandle, FlowNodeEventCallback, ffi.Pointer<ffi.Void>)>();

  FlowEventRegistrationHandle flow_graph_on_node_removed(
    FlowGraphHandle graph,
    FlowNodeEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _flow_graph_on_node_removed(
      graph,
      callback,
      user_data,
    );
  }

  late final _flow_graph_on_node_removedPtr = _lookup<
      ffi.NativeFunction<
          FlowEventRegistrationHandle Function(
              FlowGraphHandle,
              FlowNodeEventCallback,
              ffi.Pointer<ffi.Void>)>>('flow_graph_on_node_removed');
  late final _flow_graph_on_node_removed =
      _flow_graph_on_node_removedPtr.asFunction<
          FlowEventRegistrationHandle Function(
              FlowGraphHandle, FlowNodeEventCallback, ffi.Pointer<ffi.Void>)>();

  FlowEventRegistrationHandle flow_graph_on_nodes_connected(
    FlowGraphHandle graph,
    FlowConnectionEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _flow_graph_on_nodes_connected(
      graph,
      callback,
      user_data,
    );
  }

  late final _flow_graph_on_nodes_connectedPtr = _lookup<
      ffi.NativeFunction<
          FlowEventRegistrationHandle Function(
              FlowGraphHandle,
              FlowConnectionEventCallback,
              ffi.Pointer<ffi.Void>)>>('flow_graph_on_nodes_connected');
  late final _flow_graph_on_nodes_connected =
      _flow_graph_on_nodes_connectedPtr.asFunction<
          FlowEventRegistrationHandle Function(FlowGraphHandle,
              FlowConnectionEventCallback, ffi.Pointer<ffi.Void>)>();

  FlowEventRegistrationHandle flow_graph_on_nodes_disconnected(
    FlowGraphHandle graph,
    FlowConnectionEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _flow_graph_on_nodes_disconnected(
      graph,
      callback,
      user_data,
    );
  }

  late final _flow_graph_on_nodes_disconnectedPtr = _lookup<
      ffi.NativeFunction<
          FlowEventRegistrationHandle Function(
              FlowGraphHandle,
              FlowConnectionEventCallback,
              ffi.Pointer<ffi.Void>)>>('flow_graph_on_nodes_disconnected');
  late final _flow_graph_on_nodes_disconnected =
      _flow_graph_on_nodes_disconnectedPtr.asFunction<
          FlowEventRegistrationHandle Function(FlowGraphHandle,
              FlowConnectionEventCallback, ffi.Pointer<ffi.Void>)>();

  FlowEventRegistrationHandle flow_graph_on_error(
    FlowGraphHandle graph,
    FlowErrorEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _flow_graph_on_error(
      graph,
      callback,
      user_data,
    );
  }

  late final _flow_graph_on_errorPtr = _lookup<
      ffi.NativeFunction<
          FlowEventRegistrationHandle Function(
              FlowGraphHandle,
              FlowErrorEventCallback,
              ffi.Pointer<ffi.Void>)>>('flow_graph_on_error');
  late final _flow_graph_on_error = _flow_graph_on_errorPtr.asFunction<
      FlowEventRegistrationHandle Function(
          FlowGraphHandle, FlowErrorEventCallback, ffi.Pointer<ffi.Void>)>();

  FlowEventRegistrationHandle flow_node_on_compute(
    FlowNodeHandle node,
    FlowNodeEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _flow_node_on_compute(
      node,
      callback,
      user_data,
    );
  }

  late final _flow_node_on_computePtr = _lookup<
      ffi.NativeFunction<
          FlowEventRegistrationHandle Function(
              FlowNodeHandle,
              FlowNodeEventCallback,
              ffi.Pointer<ffi.Void>)>>('flow_node_on_compute');
  late final _flow_node_on_compute = _flow_node_on_computePtr.asFunction<
      FlowEventRegistrationHandle Function(
          FlowNodeHandle, FlowNodeEventCallback, ffi.Pointer<ffi.Void>)>();

  FlowEventRegistrationHandle flow_node_on_error(
    FlowNodeHandle node,
    FlowErrorEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _flow_node_on_error(
      node,
      callback,
      user_data,
    );
  }

  late final _flow_node_on_errorPtr = _lookup<
      ffi.NativeFunction<
          FlowEventRegistrationHandle Function(
              FlowNodeHandle,
              FlowErrorEventCallback,
              ffi.Pointer<ffi.Void>)>>('flow_node_on_error');
  late final _flow_node_on_error = _flow_node_on_errorPtr.asFunction<
      FlowEventRegistrationHandle Function(
          FlowNodeHandle, FlowErrorEventCallback, ffi.Pointer<ffi.Void>)>();

  FlowEventRegistrationHandle flow_node_on_set_input(
    FlowNodeHandle node,
    FlowNodeDataEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _flow_node_on_set_input(
      node,
      callback,
      user_data,
    );
  }

  late final _flow_node_on_set_inputPtr = _lookup<
      ffi.NativeFunction<
          FlowEventRegistrationHandle Function(
              FlowNodeHandle,
              FlowNodeDataEventCallback,
              ffi.Pointer<ffi.Void>)>>('flow_node_on_set_input');
  late final _flow_node_on_set_input = _flow_node_on_set_inputPtr.asFunction<
      FlowEventRegistrationHandle Function(
          FlowNodeHandle, FlowNodeDataEventCallback, ffi.Pointer<ffi.Void>)>();

  FlowEventRegistrationHandle flow_node_on_set_output(
    FlowNodeHandle node,
    FlowNodeDataEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _flow_node_on_set_output(
      node,
      callback,
      user_data,
    );
  }

  late final _flow_node_on_set_outputPtr = _lookup<
      ffi.NativeFunction<
          FlowEventRegistrationHandle Function(
              FlowNodeHandle,
              FlowNodeDataEventCallback,
              ffi.Pointer<ffi.Void>)>>('flow_node_on_set_output');
  late final _flow_node_on_set_output = _flow_node_on_set_outputPtr.asFunction<
      FlowEventRegistrationHandle Function(
          FlowNodeHandle, FlowNodeDataEventCallback, ffi.Pointer<ffi.Void>)>();

  int flow_event_unregister(
    FlowEventRegistrationHandle registration,
  ) {
    return _flow_event_unregister(
      registration,
    );
  }

  late final _flow_event_unregisterPtr = _lookup<
          ffi.NativeFunction<ffi.Int32 Function(FlowEventRegistrationHandle)>>(
      'flow_event_unregister');
  late final _flow_event_unregister = _flow_event_unregisterPtr
      .asFunction<int Function(FlowEventRegistrationHandle)>();

  bool flow_event_is_valid(
    FlowEventRegistrationHandle registration,
  ) {
    return _flow_event_is_valid(
      registration,
    );
  }

  late final _flow_event_is_validPtr = _lookup<
          ffi.NativeFunction<ffi.Bool Function(FlowEventRegistrationHandle)>>(
      'flow_event_is_valid');
  late final _flow_event_is_valid = _flow_event_is_validPtr
      .asFunction<bool Function(FlowEventRegistrationHandle)>();
}

final class max_align_t extends ffi.Opaque {}

final class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> __val;
}

abstract class FlowError {
  static const int FLOW_SUCCESS = 0;
  static const int FLOW_ERROR_INVALID_HANDLE = -1;
  static const int FLOW_ERROR_INVALID_ARGUMENT = -2;
  static const int FLOW_ERROR_NODE_NOT_FOUND = -3;
  static const int FLOW_ERROR_PORT_NOT_FOUND = -4;
  static const int FLOW_ERROR_CONNECTION_FAILED = -5;
  static const int FLOW_ERROR_MODULE_LOAD_FAILED = -6;
  static const int FLOW_ERROR_COMPUTATION_FAILED = -7;
  static const int FLOW_ERROR_OUT_OF_MEMORY = -8;
  static const int FLOW_ERROR_TYPE_MISMATCH = -9;
  static const int FLOW_ERROR_NOT_IMPLEMENTED = -10;
  static const int FLOW_ERROR_UNKNOWN = -999;
}

final class FlowGraph extends ffi.Opaque {}

final class FlowNode extends ffi.Opaque {}

final class FlowConnection extends ffi.Opaque {}

final class FlowEnv extends ffi.Opaque {}

final class FlowNodeFactory extends ffi.Opaque {}

final class FlowModule extends ffi.Opaque {}

final class FlowNodeData extends ffi.Opaque {}

final class FlowResult extends ffi.Struct {
  @ffi.Int32()
  external int error;

  external ffi.Pointer<ffi.Void> data;
}

final class FlowStringResult extends ffi.Struct {
  @ffi.Int32()
  external int error;

  external ffi.Pointer<ffi.Char> data;
}

final class FlowConnectionInfo extends ffi.Struct {
  external ffi.Pointer<ffi.Char> id;

  external ffi.Pointer<ffi.Char> source_node_id;

  external ffi.Pointer<ffi.Char> source_port_key;

  external ffi.Pointer<ffi.Char> target_node_id;

  external ffi.Pointer<ffi.Char> target_port_key;
}

typedef FlowEnvHandle = ffi.Pointer<FlowEnv>;
typedef FlowNodeFactoryHandle = ffi.Pointer<FlowNodeFactory>;
typedef FlowGraphHandle = ffi.Pointer<FlowGraph>;
typedef FlowNodeHandle = ffi.Pointer<FlowNode>;
typedef FlowConnectionHandle = ffi.Pointer<FlowConnection>;
typedef FlowNodeDataHandle = ffi.Pointer<FlowNodeData>;

final class FlowPortMetadata extends ffi.Struct {
  external ffi.Pointer<ffi.Char> key;

  external ffi.Pointer<ffi.Char> interworking_value_json;

  @ffi.Bool()
  external bool has_default;
}

typedef FlowModuleHandle = ffi.Pointer<FlowModule>;

final class FlowEventRegistration extends ffi.Opaque {}

typedef FlowEventRegistrationHandle = ffi.Pointer<FlowEventRegistration>;
typedef FlowNodeEventCallback
    = ffi.Pointer<ffi.NativeFunction<FlowNodeEventCallbackFunction>>;
typedef FlowNodeEventCallbackFunction = ffi.Void Function(
    FlowNodeHandle node, ffi.Pointer<ffi.Void> user_data);
typedef DartFlowNodeEventCallbackFunction = void Function(
    FlowNodeHandle node, ffi.Pointer<ffi.Void> user_data);
typedef FlowConnectionEventCallback
    = ffi.Pointer<ffi.NativeFunction<FlowConnectionEventCallbackFunction>>;
typedef FlowConnectionEventCallbackFunction = ffi.Void Function(
    FlowConnectionHandle conn, ffi.Pointer<ffi.Void> user_data);
typedef DartFlowConnectionEventCallbackFunction = void Function(
    FlowConnectionHandle conn, ffi.Pointer<ffi.Void> user_data);
typedef FlowErrorEventCallback
    = ffi.Pointer<ffi.NativeFunction<FlowErrorEventCallbackFunction>>;
typedef FlowErrorEventCallbackFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> error, ffi.Pointer<ffi.Void> user_data);
typedef DartFlowErrorEventCallbackFunction = void Function(
    ffi.Pointer<ffi.Char> error, ffi.Pointer<ffi.Void> user_data);
typedef FlowNodeDataEventCallback
    = ffi.Pointer<ffi.NativeFunction<FlowNodeDataEventCallbackFunction>>;
typedef FlowNodeDataEventCallbackFunction = ffi.Void Function(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
    FlowNodeDataHandle data,
    ffi.Pointer<ffi.Void> user_data);
typedef DartFlowNodeDataEventCallbackFunction = void Function(
    FlowNodeHandle node,
    ffi.Pointer<ffi.Char> port_key,
    FlowNodeDataHandle data,
    ffi.Pointer<ffi.Void> user_data);

const int true1 = 1;

const int false1 = 0;

const int __bool_true_false_are_defined = 1;

const int NULL = 0;

const int _STDINT_H = 1;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2X = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int __GLIBC_USE_C2X_STRTOL = 1;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 39;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int _BITS_STDINT_INTN_H = 1;

const int _BITS_STDINT_UINTN_H = 1;

const int _BITS_STDINT_LEAST_H = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -9223372036854775808;

const int INT_FAST32_MIN = -9223372036854775808;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 9223372036854775807;

const int INT_FAST32_MAX = 9223372036854775807;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = -1;

const int UINT_FAST32_MAX = -1;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int SIZE_MAX = -1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 4294967295;
